# Generated by Django 5.2 on 2025-04-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='main_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='webapp.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('DIS', 'Discussion')], default='LEC', max_length=3),
        ),
    ]
