# Generated by Django 5.2 on 2025-04-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_create_user', 'Can create user'), ('can_delete_user', 'Can delete user'), ('can_create_courses', 'Can create courses'), ('can_delete_courses', 'Can delete courses'), ('can_assign_courses_l1', 'Can assign courses level 1'), ('can_assign_courses_l2', 'Can assign courses level 2'))},
        ),
    ]
